apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: sb
  annotations:
    # Use a LoadBalancer type ingress class (AWS ALB in this case)
    alb.ingress.kubernetes.io/certificate-arn: "" # Leave blank if you're using the Kubernetes secret for TLS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  ingressClassName: alb
  tls:
    - hosts:
        - farseer.cloud # Your custom domain
      secretName: self-signed-cert # Kubernetes secret created earlier
  rules:
    - host: farseer.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend # Your frontend service name
                port:
                  number: 3000
