apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sb
spec:
  # type: LoadBalancer
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000