apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cloudbandits/farseer_back:latest
          ports:
            - containerPort: 8000
          env:
            - name: XAI_KEY
              valueFrom:
                secretKeyRef:
                  name: farseer-secret
                  key: XAI_KEY
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
      restartPolicy: Always